#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
fix_splits_json.py

Fix a "broken" splits JSON by removing entries (or ranges expanded from entries)
whose image and/or mask files do not exist on disk.

Supports the JSON format you showed:
  splits: { train: [ {start_image, start_label, start_frame_num, end_frame_num, ...}, ...],
            val:   [...],
            test:  [...] }

It preserves the original structure but rewrites each split list into a new list of
contiguous segments that actually exist.

It supports mixed naming schemes via:
  - filename expansion using:
      * "frameNNNN" token if present
      * otherwise the last digit-run in the stem (supports bev_C_00001.jpg)
      * preserves suffix after digits (supports bev_back_00001m.png)
  - mask resolution tries, in order:
      1) proposed label template expansion (start_label pattern)
      2) identical basename as image, in labels_dir
      3) insert 'm' before extension (same ext, then .png)
      4) legacy image_* -> label_* rewrite

Usage:
  python /app/BiSeNet/tools/fix_splits_json.py \
      --images-dir /app/BiSeNet/data_birdseye_long_selection/images \
      --labels-dir /app/BiSeNet/data_birdseye_long_selection/labels \
      --in-json /app/dataset_1_sam2autogenerated/matched.json \
      --out-json /app/BiSeNet/data_birdseye_long_selection/matched_splits.fixed.json \
      --strict-labels

Notes:
  - If you pass --strict-labels, an entry is kept only if BOTH image and label exist.
  - If you omit --strict-labels, an entry is kept if image exists (label may be resolved at train time).
"""

from __future__ import annotations

import argparse
import json
import os
import os.path as osp
import re
from dataclasses import dataclass
from typing import Any, Dict, List, Optional, Tuple


def build_name_from_template(template_name: str, frame: int) -> str:
    """
    Replace the index portion in a filename template.

    Supports:
      1) image_..._frame004401.jpg  -> replace digits after 'frame'
      2) bev_C_00001.jpg            -> replace the LAST digit-run in the stem
      3) bev_back_00001m.png        -> same as (2), preserves trailing 'm'
      4) frame007.jpg               -> same as (2)

    Returns only the basename (no directories).
    """
    base = osp.basename(template_name)

    m = re.search(r"(frame)(\d+)", base)
    if m:
        pad = len(m.group(2))
        return re.sub(r"frame\d+", f"frame{frame:0{pad}d}", base, count=1)

    stem, ext = osp.splitext(base)
    m2 = re.search(r"(\d+)(\D*)$", stem)
    if not m2:
        raise ValueError(f"Template has no 'frameNNNN' token and no trailing digits: {template_name}")

    digits = m2.group(1)
    suffix = m2.group(2)
    pad = len(digits)

    new_stem = stem[: m2.start(1)] + f"{frame:0{pad}d}" + suffix
    return new_stem + ext


def candidate_label_paths(labels_dir: str, img_path: str) -> List[str]:
    img_base = osp.basename(img_path)
    stem, ext = osp.splitext(img_base)

    cands = [
        osp.join(labels_dir, img_base),                # identical filename
        osp.join(labels_dir, f"{stem}m{ext}"),         # insert 'm' before ext, same ext
        osp.join(labels_dir, f"{stem}m.png"),          # insert 'm' and use png
    ]

    if stem.startswith("image_"):
        cands.append(osp.join(labels_dir, f"label_{stem[len('image_') :]}{ext}"))
        cands.append(osp.join(labels_dir, f"label_{stem[len('image_') :]}.png"))

    return cands


def resolve_label_path(labels_dir: str, img_path: str, proposed_label_path: Optional[str]) -> Optional[str]:
    if proposed_label_path and osp.isfile(proposed_label_path):
        return proposed_label_path

    for p in candidate_label_paths(labels_dir, img_path):
        if osp.isfile(p):
            return p
    return None


@dataclass
class SegmentMeta:
    matched: Optional[bool] = None
    match_key: Optional[str] = None


def segment_template_matches_only_one_frame(seg: Dict[str, Any]) -> bool:
    # Common case in your sample: count=1, start_frame_num=end_frame_num
    return int(seg.get("start_frame_num", 0)) == int(seg.get("end_frame_num", 0))


def make_segment(
    start_image: str,
    end_image: str,
    start_label: str,
    end_label: str,
    start_frame_num: int,
    end_frame_num: int,
    meta_src: Dict[str, Any],
    count: Optional[int] = None,
) -> Dict[str, Any]:
    out = dict(meta_src)  # shallow copy preserves extra keys you have
    out["start_image"] = start_image
    out["end_image"] = end_image
    out["start_label"] = start_label
    out["end_label"] = end_label
    out["start_frame_num"] = int(start_frame_num)
    out["end_frame_num"] = int(end_frame_num)
    out["count"] = int(count if count is not None else (end_frame_num - start_frame_num + 1))
    return out


def compress_frames_to_segments(
    frames: List[Tuple[int, str, str]],
    meta_src: Dict[str, Any],
) -> List[Dict[str, Any]]:
    """
    frames: list of (frame_num, image_basename, label_basename) sorted by frame_num.
    Produce contiguous segments where BOTH image and label naming templates are stable
    enough to express as start_* plus frame range.

    Since the dataset class can already build per-frame names from the start template,
    we can store segment start_* as the first basename, and rely on build_name_from_template.
    """
    if not frames:
        return []

    # Sort by frame number
    frames = sorted(frames, key=lambda x: x[0])

    out: List[Dict[str, Any]] = []
    run_start_idx = 0

    def flush(run_start: int, run_end: int):
        f0 = frames[run_start]
        f1 = frames[run_end]
        start_frame = f0[0]
        end_frame = f1[0]
        seg = make_segment(
            start_image=f0[1],
            end_image=f1[1],
            start_label=f0[2],
            end_label=f1[2],
            start_frame_num=start_frame,
            end_frame_num=end_frame,
            meta_src=meta_src,
            count=(end_frame - start_frame + 1),
        )
        out.append(seg)

    for i in range(1, len(frames)):
        prev = frames[i - 1]
        cur = frames[i]
        # contiguous frame numbers?
        if cur[0] != prev[0] + 1:
            flush(run_start_idx, i - 1)
            run_start_idx = i
            continue

        # ensure that the naming template can generate the current basenames
        # from the run's start basenames. If not, split.
        run_start = frames[run_start_idx]
        try:
            exp_img = build_name_from_template(run_start[1], cur[0])
            exp_lb = build_name_from_template(run_start[2], cur[0])
        except Exception:
            flush(run_start_idx, i - 1)
            run_start_idx = i
            continue

        if exp_img != cur[1] or exp_lb != cur[2]:
            flush(run_start_idx, i - 1)
            run_start_idx = i
            continue

    flush(run_start_idx, len(frames) - 1)
    return out


def fix_split(
    split_segments: List[Dict[str, Any]],
    images_dir: str,
    labels_dir: str,
    strict_labels: bool,
    verbose: bool,
) -> Tuple[List[Dict[str, Any]], Dict[str, int]]:
    kept_frames: List[Tuple[int, str, str]] = []
    stats = {
        "segments_in": len(split_segments),
        "frames_total": 0,
        "frames_kept": 0,
        "frames_missing_image": 0,
        "frames_missing_label": 0,
        "segments_out": 0,
    }

    # Keep extra keys from the first segment as "meta template" for output segments.
    # We preserve any extra keys present (matched/match_key/etc.) per segment by copying
    # from the source segment that produced each run. For simplicity, we compress within
    # each original segment separately (so metadata stays aligned).
    out_segments: List[Dict[str, Any]] = []

    for seg in split_segments:
        start = int(seg["start_frame_num"])
        end = int(seg["end_frame_num"])
        img_template = str(seg["start_image"])
        lb_template = str(seg["start_label"])

        local_kept: List[Tuple[int, str, str]] = []

        for frame in range(start, end + 1):
            stats["frames_total"] += 1

            try:
                img_name = build_name_from_template(img_template, frame)
            except Exception as e:
                # If template can't generate names, treat as missing and move on
                stats["frames_missing_image"] += 1
                if verbose:
                    print(f"[warn] cannot build image name from template={img_template} frame={frame}: {e}")
                continue

            img_path = osp.join(images_dir, img_name)
            if not osp.isfile(img_path):
                stats["frames_missing_image"] += 1
                if verbose:
                    print(f"[miss image] {img_path}")
                continue

            # Proposed label from template
            proposed_label_path = None
            try:
                lb_name = build_name_from_template(lb_template, frame)
                proposed_label_path = osp.join(labels_dir, lb_name)
            except Exception:
                proposed_label_path = None

            resolved = resolve_label_path(labels_dir, img_path, proposed_label_path)
            if resolved is None:
                stats["frames_missing_label"] += 1
                if strict_labels:
                    if verbose:
                        print(f"[miss label] image={img_path}")
                    continue
                # non-strict: keep image; for label store the proposed basename if available else same as image basename
                resolved = proposed_label_path or osp.join(labels_dir, osp.basename(img_path))

            local_kept.append((frame, osp.basename(img_path), osp.basename(resolved)))

        # compress kept frames from THIS segment into output segments (preserve seg meta keys)
        out_segments.extend(compress_frames_to_segments(local_kept, meta_src=seg))

        stats["frames_kept"] += len(local_kept)

    stats["segments_out"] = len(out_segments)
    return out_segments, stats


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--images-dir", required=True, help="Absolute path to images directory")
    ap.add_argument("--labels-dir", required=True, help="Absolute path to labels directory")
    ap.add_argument("--in-json", required=True, help="Input (broken) splits json")
    ap.add_argument("--out-json", required=True, help="Output (fixed) splits json")
    ap.add_argument("--strict-labels", action="store_true", help="Drop samples if label can't be found")
    ap.add_argument("--verbose", action="store_true", help="Print missing files while fixing")
    args = ap.parse_args()

    images_dir = osp.abspath(args.images_dir)
    labels_dir = osp.abspath(args.labels_dir)
    in_json = osp.abspath(args.in_json)
    out_json = osp.abspath(args.out_json)

    if not osp.isdir(images_dir):
        raise FileNotFoundError(f"images-dir not found: {images_dir}")
    if not osp.isdir(labels_dir):
        raise FileNotFoundError(f"labels-dir not found: {labels_dir}")
    if not osp.isfile(in_json):
        raise FileNotFoundError(f"in-json not found: {in_json}")

    with open(in_json, "r", encoding="utf-8") as f:
        spec = json.load(f)

    if "splits" not in spec or not isinstance(spec["splits"], dict):
        raise KeyError("Input JSON missing top-level 'splits' dict")

    new_spec = dict(spec)  # shallow copy
    new_splits: Dict[str, Any] = {}

    all_stats: Dict[str, Dict[str, int]] = {}

    for split_name in ("train", "val", "test"):
        segs = spec["splits"].get(split_name, [])
        if not segs:
            new_splits[split_name] = []
            all_stats[split_name] = {
                "segments_in": 0, "frames_total": 0, "frames_kept": 0,
                "frames_missing_image": 0, "frames_missing_label": 0,
                "segments_out": 0,
            }
            continue

        fixed, stats = fix_split(
            split_segments=segs,
            images_dir=images_dir,
            labels_dir=labels_dir,
            strict_labels=args.strict_labels,
            verbose=args.verbose,
        )
        new_splits[split_name] = fixed
        all_stats[split_name] = stats

    new_spec["splits"] = new_splits
    new_spec["fixed_from"] = {
        "images_dir": images_dir,
        "labels_dir": labels_dir,
        "input_json": in_json,
        "strict_labels": bool(args.strict_labels),
    }
    new_spec["fix_stats"] = all_stats

    os.makedirs(osp.dirname(out_json), exist_ok=True)
    with open(out_json, "w", encoding="utf-8") as f:
        json.dump(new_spec, f, indent=2)

    # Print summary
    for split_name, s in all_stats.items():
        print(
            f"{split_name}: segments {s['segments_in']} -> {s['segments_out']}, "
            f"frames kept {s['frames_kept']}/{s['frames_total']}, "
            f"missing image {s['frames_missing_image']}, missing label {s['frames_missing_label']}"
        )
    print(f"Wrote: {out_json}")


if __name__ == "__main__":
    main()
