# cfg = dict(
#     model_type='bisenetv2',

#     # Set this to the number of classes produced by your label decoding.
#     # If you are currently decoding as binary, keep 2.
#     n_cats=2,

#     num_aux_heads=4,
#     lr_start=5e-4,
#     weight_decay=1e-3,
#     warmup_iters=3000,
#     checkpoint_interval=250,
#     val_interval=  250,
#     val_num_batches=100,  # optional, for speed
#     max_iter=200000,
#     dataset = "MergedJsonDataset",

#     datasets = [
#     {"images_dir": "/app/dataset_1_sam2autogenerated_png/images", "labels_dir": "/app/dataset_1_sam2autogenerated_png/labels", "annpath": "/app/dataset_1_sam2autogenerated_png/merged_splits.json"},
#     {"images_dir": "/app/mar15th_data/m15/images", "labels_dir": "/app/mar15th_data/m15/labels", "annpath": "/app/mar15th_data/m15/m15_splits_all.json"},

#    {"images_dir": "/app/BiSeNet/data_birdseye_long_selection/images", "labels_dir": "/app/BiSeNet/data_birdseye_long_selection/labels", "annpath": "/app/BiSeNet/data_birdseye_long_selection/matched_splits.fixed2.json"},

#     {"images_dir": "/app/birdseye_run_6/frames/rgb", "labels_dir": "/app/birdseye_run_6/frames/mask", "annpath": "/app/birdseye_run_6/generated_splits.json"},
#     {"images_dir": "/app/birdseye_run_7/frames/rgb", "labels_dir": "/app/birdseye_run_7/frames/mask", "annpath": "/app/birdseye_run_7/generated_splits.json"},
#     {"images_dir": "/app/birdseye_run_9/frames/output_rgb", "labels_dir": "/app/birdseye_run_9/frames/output_mask", "annpath": "/app/birdseye_run_9/generated_splits.json"},




#     ],
#     lb_ignore = 255,  # when this is used in the pipeline land is 0 water is 1...this is not saying ignore values of 255 in the original image


#     scales=[1.0, 1.0],
#     cropsize=[1184, 896],
#     eval_crop=[1184, 896],
#     # eval_scales=[0.5, 0.75, 1.0, 1.25, 1.5, 1.75],
#     eval_scales=[1.0, 1.0],


#     ims_per_gpu=2,
#     eval_ims_per_gpu=2,
#     use_fp16=True,
#     use_sync_bn=False,

#     wandb=True,
#     wandb_project="bisenetv2-BEV",
#     wandb_entity=None,
#     wandb_run_name="BEV Model without compression issues (run 6-7-8 sim + sam2 + hand + semi-synthetic augmentations)",
#     wandb_notes="new multi dataset run; doesn't include recently implemented augmentations; will be included in identical separate run",
#     wandb_tags=["amp", "ddp"],
# )



# THIS IS A COPY OF THE PARAMETER STATE WHEN THE MODEL WAS TRAINED; DO NOT MODIFY

cfg = dict(
    model_type='bisenetv2',

    # Set this to the number of classes produced by your label decoding.
    # If you are currently decoding as binary, keep 2.
    n_cats=2,

    num_aux_heads=4,
    lr_start=1e-3,
    weight_decay=5e-4,
    warmup_iters=1000,
    checkpoint_interval=250,
    val_interval=  250,
    val_num_batches=100,  # optional, for speed
    max_iter=200000,
    dataset = "MergedJsonDataset",

    datasets = [
    # {"images_dir": "/app/dataset_1_sam2autogenerated_png/images", "labels_dir": "/app/dataset_1_sam2autogenerated_png/labels", "annpath": "/app/dataset_1_sam2autogenerated_png/merged_splits.json"},
    {"images_dir": "/app/mar15th_data/m15/images", "labels_dir": "/app/mar15th_data/m15/labels", "annpath": "/app/mar15th_data/m15/m15_splits_all.json"},

   {"images_dir": "/app/BiSeNet/data_birdseye_long_selection/images", "labels_dir": "/app/BiSeNet/data_birdseye_long_selection/labels", "annpath": "/app/BiSeNet/data_birdseye_long_selection/matched_splits.fixed2.json"},

    {"images_dir": "/app/birdseye_run_6/frames/rgb", "labels_dir": "/app/birdseye_run_6/frames/mask", "annpath": "/app/birdseye_run_6/generated_splits.json"},
    {"images_dir": "/app/birdseye_run_7/frames/rgb", "labels_dir": "/app/birdseye_run_7/frames/mask", "annpath": "/app/birdseye_run_7/generated_splits.json"},
    {"images_dir": "/app/birdseye_run_9/frames/output_rgb", "labels_dir": "/app/birdseye_run_9/frames/output_mask", "annpath": "/app/birdseye_run_9/generated_splits.json"},




    ],


    # dataset = "MergedJsonDataset"  # keep this if you want; loader below uses it only for legacy fallback
    lb_ignore = -205,  # only matters if loss uses ignore_index; safe if decoded labels are 0/1


    scales=[0.75, 2.0],
    cropsize= [512, 512],
    # cropsize=[896, 1184],
    eval_crop=[512, 512],
    # eval_scales=[0.5, 0.75, 1.0, 1.25, 1.5, 1.75],
    eval_scales=[0.5, 1.0, 1.5],


    ims_per_gpu=8,
    eval_ims_per_gpu=2,
    use_fp16=True,
    use_sync_bn=False,

    wandb=True,
    wandb_project="bisenetv2-BEV",
    wandb_entity=None,
    wandb_run_name="continued training btd",
    wandb_notes="augmentations included",
    wandb_tags=["amp", "ddp"],
)

